name: API Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip pipenv -y
          pipenv install fastapi uvicorn pytest requests

      - name: Start FastAPI server
        run: pipenv run python3 apiserver.py &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server to be ready
        run: sleep 5  # Ensures the server is up before running tests

      - name: Run tests
        run: pipenv run pytest automation_test_pytest.py